sudo: required

services:
  - docker

before_install:
  - sudo service postgresql stop
  - echo '{"build": "$TRAVIS_BUILD_NUMBER", "git": "$TRAVIS_COMMIT"}' > ./buildinfo.json
  - make start
  - docker-compose -f docker-compose.dev.yml ps
  - wget --spider -S "http://localhost:8000/api/users/"
#  - make waitforserver

script:
  - make yarn test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push twentyfifth/ttrack-server;
    fi