version: '2'

services:
  test-db:
    image: postgres:9.5
    container_name: ttrack-test-db
    environment:
      - POSTGRES_DB=ttrack
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  test-ttrack:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ttrack-test-app
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_DATABASE=ttrack
      - DB_HOST=test-db
      - NODE_ENV=development
    ports:
      - 8090:8080
    volumes:
      - ./src:/app/src
      - ./public/images/users:/app/public/images/users