version: '2.1'
services:
  hapi-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - AS_USER=${AS_USER:-root}
        - AS_GID=${AS_GID:-0}
        - AS_UID=${AS_UID:-0}
    image: twentyfifth/hapi-server:latest
    container_name: hapi-server
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ${PWD}:/usr/src/app