version: '2'

services:
  db:
    image: postgres:9.5
    container_name: ttrack-db
    environment:
      - POSTGRES_DB=ttrack
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  ttrack-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ttrack-server
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_DATABASE=ttrack
      - DB_HOST=db
      - NODE_ENV=development
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
    depends_on:
      - db
